package fasttracklogistics.model;

import java.time.LocalDateTime;

public class Delivery {
    private int deliveryId;
    private int shipmentId; // FK to Shipment
    private int personnelId; // FK to DeliveryPersonnel
    private LocalDateTime scheduledPickupTime;
    private LocalDateTime actualPickupTime;
    private LocalDateTime scheduledDeliveryTime;
    private LocalDateTime actualDeliveryTime;
    private String deliveryStatus; // e.g., "Scheduled", "Picked Up", "In Transit", "Delivered", "Failed"
    private String routeDetails; // Simple string or could be a separate Route model
    private String deliveryNotes;

    // Default Constructor
    public Delivery() {
    }

    // Constructor for scheduling a new delivery (ID often auto-generated by DB)
    public Delivery(int shipmentId, int personnelId, LocalDateTime scheduledPickupTime,
                    LocalDateTime scheduledDeliveryTime, String deliveryStatus, String routeDetails, String deliveryNotes) {
        this.shipmentId = shipmentId;
        this.personnelId = personnelId;
        this.scheduledPickupTime = scheduledPickupTime;
        this.scheduledDeliveryTime = scheduledDeliveryTime;
        this.deliveryStatus = deliveryStatus;
        this.routeDetails = routeDetails;
        this.deliveryNotes = deliveryNotes;
    }

    // Full Constructor (e.g., when retrieving from DB)
    public Delivery(int deliveryId, int shipmentId, int personnelId, LocalDateTime scheduledPickupTime,
                    LocalDateTime actualPickupTime, LocalDateTime scheduledDeliveryTime,
                    LocalDateTime actualDeliveryTime, String deliveryStatus, String routeDetails, String deliveryNotes) {
        this(shipmentId, personnelId, scheduledPickupTime, scheduledDeliveryTime, deliveryStatus, routeDetails, deliveryNotes);
        this.deliveryId = deliveryId;
        this.actualPickupTime = actualPickupTime;
        this.actualDeliveryTime = actualDeliveryTime;
    }

    // Getters and Setters
    public int getDeliveryId() { return deliveryId; }
    public void setDeliveryId(int deliveryId) { this.deliveryId = deliveryId; }

    public int getShipmentId() { return shipmentId; }
    public void setShipmentId(int shipmentId) { this.shipmentId = shipmentId; }

    public int getPersonnelId() { return personnelId; }
    public void setPersonnelId(int personnelId) { this.personnelId = personnelId; }

    public LocalDateTime getScheduledPickupTime() { return scheduledPickupTime; }
    public void setScheduledPickupTime(LocalDateTime scheduledPickupTime) { this.scheduledPickupTime = scheduledPickupTime; }

    public LocalDateTime getActualPickupTime() { return actualPickupTime; }
    public void setActualPickupTime(LocalDateTime actualPickupTime) { this.actualPickupTime = actualPickupTime; }

    public LocalDateTime getScheduledDeliveryTime() { return scheduledDeliveryTime; }
    public void setScheduledDeliveryTime(LocalDateTime scheduledDeliveryTime) { this.scheduledDeliveryTime = scheduledDeliveryTime; }

    public LocalDateTime getActualDeliveryTime() { return actualDeliveryTime; }
    public void setActualDeliveryTime(LocalDateTime actualDeliveryTime) { this.actualDeliveryTime = actualDeliveryTime; }

    public String getDeliveryStatus() { return deliveryStatus; }
    public void setDeliveryStatus(String deliveryStatus) { this.deliveryStatus = deliveryStatus; }

    public String getRouteDetails() { return routeDetails; }
    public void setRouteDetails(String routeDetails) { this.routeDetails = routeDetails; }

    public String getDeliveryNotes() { return deliveryNotes; }
    public void setDeliveryNotes(String deliveryNotes) { this.deliveryNotes = deliveryNotes; }

    @Override
    public String toString() {
        return "Delivery{" +
                "deliveryId=" + deliveryId +
                ", shipmentId=" + shipmentId +
                ", personnelId=" + personnelId +
                ", deliveryStatus='" + deliveryStatus + '\'' +
                '}';
    }
}