package fasttracklogistics.model;

public class DeliveryPersonnel {
    private int personnelId;
    private String name;
    private String contactInfo; // e.g., phone number, email
    private String personnelType; // e.g., Driver, Courier
    private String licenseNumber;
    private String vehicleDetails; // e.g., 'Toyota Hiace, ABC-1234'
    private String availabilityStatus; // e.g., "Available", "On Duty", "Off Duty", "Break"

    // Default Constructor
    public DeliveryPersonnel() {
    }

    // Constructor for creating new personnel (ID often auto-generated by DB)
    public DeliveryPersonnel(String name, String contactInfo, String personnelType,
                             String licenseNumber, String vehicleDetails, String availabilityStatus) {
        this.name = name;
        this.contactInfo = contactInfo;
        this.personnelType = personnelType;
        this.licenseNumber = licenseNumber;
        this.vehicleDetails = vehicleDetails;
        this.availabilityStatus = availabilityStatus;
    }

    // Full Constructor (e.g., when retrieving from DB)
    public DeliveryPersonnel(int personnelId, String name, String contactInfo, String personnelType,
                             String licenseNumber, String vehicleDetails, String availabilityStatus) {
        this(name, contactInfo, personnelType, licenseNumber, vehicleDetails, availabilityStatus);
        this.personnelId = personnelId;
    }

    // Getters and Setters
    public int getPersonnelId() { return personnelId; }
    public void setPersonnelId(int personnelId) { this.personnelId = personnelId; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getContactInfo() { return contactInfo; }
    public void setContactInfo(String contactInfo) { this.contactInfo = contactInfo; }

    public String getPersonnelType() { return personnelType; }
    public void setPersonnelType(String personnelType) { this.personnelType = personnelType; }

    public String getLicenseNumber() { return licenseNumber; }
    public void setLicenseNumber(String licenseNumber) { this.licenseNumber = licenseNumber; }

    public String getVehicleDetails() { return vehicleDetails; }
    public void setVehicleDetails(String vehicleDetails) { this.vehicleDetails = vehicleDetails; }

    public String getAvailabilityStatus() { return availabilityStatus; }
    public void setAvailabilityStatus(String availabilityStatus) { this.availabilityStatus = availabilityStatus; }

    @Override
    public String toString() {
        return "DeliveryPersonnel{" +
                "personnelId=" + personnelId +
                ", name='" + name + '\'' +
                ", availabilityStatus='" + availabilityStatus + '\'' +
                '}';
    }
}